"use client";
import Header from "./components/Header";
import Provider from "./components/Provider";
import "./styles/globals.css";

export const metadata = {
  title: "Lista Tarefas",
  description: "Generated by create next app",
};

interface IProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: IProps) {
  return (
    <html lang="pt-br">
      <body>
        <Provider>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  );
}
